// angular-frontend/angular_frontend/src/app/create-employee/create-employee.component.ts
import { Component, OnInit } from '@angular/core';
import { Employee } from '../employee';
import { EmployeeService } from '../employee.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-create-employee',
  templateUrl: './create-employee.component.html',
  styleUrls: ['./create-employee.component.css'],
})
export class CreateEmployeeComponent implements OnInit {
  employee: Employee = new Employee();
  constructor(
    private employeeService: EmployeeService,
    private router: Router
  ) {}
  ngOnInit(): void {}
  saveEmployee() {
    this.employeeService.createEmployee(this.employee).subscribe(
      (data) => {
        console.log(data);
        this.goToEmployeeList();
      },
      (error) => console.log(error)
    );
  }
  goToEmployeeList() {
    this.router.navigate(['employees']);
  }
  onSubmit() {
    console.log(this.employee);
    this.saveEmployee();
  }
}

<div class="col-md-6 offset-md-3">
  <h3>Create Employee</h3>
  <form (ngSubmit)="onSubmit()">
    <div class="form-group">
      <label> First Name</label>
      <input
        type="text"
        class="form-control"
        id="firstName"
        [(ngModel)]="employee.firstName"
        name="firstName"
      />
    </div>

    <div class="form-group">
      <label> Last Name</label>
      <input
        type="text"
        class="form-control"
        id="lastName"
        [(ngModel)]="employee.lastName"
        name="lastName"
      />
    </div>

    <div class="form-group">
      <label> Email Id</label>
      <input
        type="text"
        class="form-control"
        id="emailId"
        [(ngModel)]="employee.emailId"
        name="emailId"
      />
    </div>

    <!-- <div class="form-group">
      <label> Birth Date </label>
      <input
        type="text"
        class="form-control"
        id="birthdate"
        [(ngModel)]="employee.birthdate"
        name="birthdate"
      />
    </div> -->

    <button class="btn btn-success" type="submit">Submit</button>
  </form>
</div>

// react-frontend/src/component/CreateEmployeeComponent.jsx
import React, { Component } from "react";
import { Link, Navigate } from "react-router-dom";
import EmployeeService from "../service/EmployeeService";
import "./EmployeeForm.css";
class CreateEmployeeComponent extends Component {
  constructor(props) {
    super(props);
    this.state = {
      firstName: "",
      lastName: "",
      emailId: "",
      registrationSuccessful: false,
    };

    this.changeFirstNameHandler = this.changeFirstNameHandler.bind(this);
    this.changeLastNameHandler = this.changeLastNameHandler.bind(this);
    this.changeEmailHandler = this.changeEmailHandler.bind(this);
    this.saveEmployee = this.saveEmployee.bind(this);
  }

  changeFirstNameHandler(event) {
    this.setState({ firstName: event.target.value });
  }

  changeLastNameHandler(event) {
    this.setState({ lastName: event.target.value });
  }

  changeEmailHandler(event) {
    this.setState({ emailId: event.target.value });
  }

  saveEmployee(e) {
    e.preventDefault();
    const employee = {
      firstName: this.state.firstName,
      lastName: this.state.lastName,
      emailId: this.state.emailId,
    };
    console.log("employee => " + JSON.stringify(employee));
    EmployeeService.saveEmployee(employee).then((res) => {
      this.setState({ registrationSuccessful: true });
    });
  }

  render() {
    if (this.state.registrationSuccessful) {
      return <Navigate to="/" />;
    }

    return (
      <div>
        <div className="container">
          <div className="row">
            <div className="card col-md-6 offset-md-3">
              <h3 className="text-center">Add new Employee!</h3>
              <div className="card-body">
                <form>
                  <div className="form-group">
                    <label>First Name:</label>
                    <input
                      placeholder="enter first name"
                      name="firstName"
                      className="form-control"
                      value={this.state.firstName}
                      onChange={this.changeFirstNameHandler}
                    />
                  </div>
                  <div className="form-group">
                    <label>Last Name:</label>
                    <input
                      placeholder="enter last name"
                      name="lastName"
                      className="form-control"
                      value={this.state.lastName}
                      onChange={this.changeLastNameHandler}
                    />
                  </div>
                  <div className="form-group">
                    <label>Email-Id:</label>
                    <input
                      placeholder="enter email"
                      name="email"
                      className="form-control"
                      value={this.state.emailId}
                      onChange={this.changeEmailHandler}
                    />
                  </div>
                  <div>
                    <Link
                      className="btn btn-success"
                      onClick={this.saveEmployee}
                    >
                      save
                    </Link>
                    <Link
                      to="/"
                      className="btn btn-danger"
                      style={{ marginLeft: "10px" }}
                    >
                      Cancel
                    </Link>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default CreateEmployeeComponent;
